# Referencias

En esta sección se presenta el conjunto de referencias utilizadas en el desarrollo de *SCAHpy*, incluyendo documentación científica del sistema **IGP RESM-COW**, modelos numéricos base y, herramientas de software científico.

## Cómo citar SCAHpy?

Si deseas citar SCAHpy en trabajos académicos, de momento recomendamos emplear el siguiente Avance de Investigación publicado en el Boletín Científico del IGP:

> Castillón, F., y Montes, I. (2024). Herramienta para el posprocesamiento de los datos numéricos de modelos regionales: SCAHpy. Boletín científico El Niño, Instituto Geofísico del Perú, 11 (03), 13-17. <http://hdl.handle.net/20.500.12816/5707>

Pronto un paper ;)!

## Referencias del sistema IGP RESM-COW

Puede consultarse en los siguientes documentos institucionales:

* Castillón, F., Berlin, S., y Montes, I. (2023). Validación de la componente atmosférica del sistema acoplado regional océano-atmósfera del Pacífico sudeste. Boletín científico El Niño, Instituto Geofísico del Perú, 10 (1), 9-12. <http://hdl.handle.net/20.500.12816/5406>

* Segura, B., Montes, I., Castillón, F., Manay R. y Takahashi, K. (2023). Implementación del componente acoplado océano-atmósfera del Modelo Regional del Sistema Tierra (RESM) en modo pronóstico para el territorio peruano y el océano Pacífico oriental: periodo enero-julio 2023. Boletín científico El Niño, Instituto Geofísico del Perú, 10 (11), 10-13. <http://hdl.handle.net/20.500.12816/5568>

* Segura, B. y Montes, I. (2021). Análisis de sensibilidad del sistema acoplado regional COW para el Pacífico sudeste. Boletín científico El Niño, Instituto Geofísico del Perú, 8 (2), 12-17. <http://hdl.handle.net/20.500.12816/5327>

* Segura, B., Montes, I. y Mosquera, K. (2014). Evolución del Sistema Computacional de Alto Rendimiento en el IGP para un mejor pronóstico y estudio de los fenómenos climáticos. Boletín técnico: Generación de modelos climáticos para el pronóstico de la ocurrencia del Fenómeno El Niño, Instituto Geofísico del Perú, 1 (11), 8-9. <http://hdl.handle.net/20.500.12816/4647>

---

## Referencias de modelos numéricos

* [Modelo WRF](https://www2.mmm.ucar.edu/wrf/users/)
* [Modelo CROCO](https://www.croco-ocean.org/)
* [Acoplador Oasis](https://oasis.cerfacs.fr/en/home/)

---

## Software científico utilizado

SCAHpy se apoya en los paquetes fundamentales de Python:

* [xarray](https://docs.xarray.dev/en/stable/index.html)
* [dask](https://docs.dask.org/en/stable/index.html)
* [netCDF4](https://unidata.github.io/netcdf4-python/#introduction)
* [numpy](https://numpy.org/)
* [matplotlib](https://matplotlib.org/)
* [pandas](https://pandas.pydata.org/)
* [cartopy](https://pypi.org/project/Cartopy/)
* [pyshp](https://pypi.org/project/pyshp/)
* [cmocean](https://matplotlib.org/cmocean/) y [crameri](https://www.fabiocrameri.ch/colourmaps/) (Opcionales para paletas de color bonitas)
